### PR TITLE
modify 'ipex' backend

### PR DESCRIPTION
**Pull request by jiayisunx**
Modify ’ipex‘ backend:
1. Support two datatypes: float32 and bfloat16,
2. JIT trace to obtain more optimization opportunities, such as fusion, weights prepack etc.

### CODE REVIEW

**Comment by jiayisunx** [comment]
I would like add some UTs if necessary, and please give me a suitable location for IPEX UTs.

**Comment by jansel** [comment]
Thanks for improving that!

You can put the unit tests in `tests/test_optimizations.py`.  Make sure to wrap then in a `unittest.skipIf` that checks if ipex is installed in the user's environment.

For the lint errors, you can fix them with:
```
make lint-deps
make format
make lint
```

**Comment by jiayisunx** [comment]
@jansel , I have added UTs for 'ipex' backend, please help review it again, thanks.

**Review by jansel — CHANGES_REQUESTED** [review]
Looks good to me.

There are a few small lints here: https://github.com/facebookresearch/torchdynamo/runs/6160744527?check_suite_focus=true#step:5:12

Can you fix those then I'll merge it?

**Review by jansel — APPROVED** [review]

**Comment by jansel** [comment]
Thanks!

**Pull request merged**
