### PR TITLE
add an option to randomize inputs

### PR DESCRIPTION
**Pull request by shunting314**
torchbench only provides a single set of input for each model so far. We can not discover issues like caching something we should not cache. This PR add an option to torchbench.py in dynamo repo to generate randomized input.

Note that, we only randomize floating point items. For integral items, randomizing it may generate invalid inputs especially when those integral items representing indices.

The PR also adapt the ltc/ltc_trivial backend to the refactoring made inside LTC recently.

Test plan:
```
LTC_TS_CUDA=1 gpui time python torchbench.py --speedup-ltc -dcuda --nvfuser --randomize-input
```

cc @jansel

### CODE REVIEW

**Comment by xuzhao9** [comment]
> torchbench only provides a single set of input for each model so far. We can not discover issues like caching something we should not cache. This PR add an option to torchbench to generate randomized input.
> 
> Note that, we only randomize floating point items. For integral items, randomizing it may generate invalid inputs especially when those integral items representing indices.
> 
> The PR also adapt the ltc/ltc_trivial backend to the refactoring made inside LTC recently.
> 
> Test plan:
> 
> ```
> LTC_TS_CUDA=1 gpui time python torchbench.py --speedup-ltc -dcuda --nvfuser --randomize-input
> ```
> 
> cc @jansel

TorchBench has added an interface, `gen_inputs()`, which will return another set of inputs for the model. It currently only supports timm and vision models, but we are working towards 100% coverage.

**Comment by anijain2305** [comment]
Does it make sense to change the example inputs here - https://github.com/facebookresearch/torchdynamo/blob/main/torchbench.py#L145-L149

This way, you can use randomize inputs for any of the speedup experiments.

**Review by jansel — APPROVED** [review]
lgtm

**Comment by xuzhao9** [comment]
> 

Yes, it makes sense to change the example inputs there.

**Comment by shunting314** [comment]
> Does it make sense to change the example inputs here - https://github.com/facebookresearch/torchdynamo/blob/main/torchbench.py#L145-L149
> 
> This way, you can use randomize inputs for any of the speedup experiments.

The problem is we need multiple random inputs while the load_model interface only return a single input. We wound need to change the interface/behavior of this method which may break callers.

**Comment by xuzhao9** [comment]
>  The problem is we need multiple random inputs while the load_model interface only return a single input. We wound need to change the interface/behavior of this method which may break callers.

First, I am okay to merge this without using `gen_inputs()`.
Second, I think it makes sense to change the interface of this method from returning a single input to returning an input generator, but this can be an optional improvement later.

**Review by anijain2305 — APPROVED** [review]

**Comment by shunting314** [comment]
> Second, I think it makes sense to change the interface of this method from returning a single input to returning an input generator, but this can be an optional improvement later.

For the second point, should we worry about the caller side. Assume there are other callers to this method. Originally they expect a single batch but now they get an generator/iterator of batches. We would need a way to handle this backward compatibility.

**Comment by shunting314** [comment]
@jansel  @anijain2305  looks like I don't have permission to merge to the facebookresearch/torchdynamo repo. Do you mind do the merge for me?

**Comment by xuzhao9** [comment]
Merged

**Pull request merged**
